TITLE = "Memory puzzle"
FPS = 30

BOX_SIZE = 40
GAP_SIZE = 10
TILES_ON_HEIGHT = 5
TILES_ON_WIDTH = 4

WINDOW_WIDTH = (BOX_SIZE+GAP_SIZE) * TILES_ON_WIDTH + GAP_SIZE
WINDOW_HEIGHT = (BOX_SIZE+GAP_SIZE) * TILES_ON_HEIGHT + GAP_SIZE

RESOLUTION = (WINDOW_WIDTH, WINDOW_HEIGHT)

X_MARGIN = GAP_SIZE
Y_MARGIN = GAP_SIZE


REVEAL_SPEED = 8

BOXES_OPEN_SPEED = 8
GRAY = (100, 100, 100)
NAVYBLUE = (60, 60, 100)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 128, 0)
PURPLE = (255, 0, 255)
CYAN = (0, 255, 255)


BG_COLOR = NAVYBLUE
LIGHT_BG_COLOR = GRAY
BOX_COLOR = WHITE
HIGHLIGHT_COLOR = BLUE
BOARD_COLOR = GRAY

DONUT = "donut"
SQUARE = "square"
DIAMOND = "diamond"
LINES = "lines"
OVAL = "oval"

ALL_COLORS = (RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE, CYAN)
ALL_SHAPES = (DONUT, SQUARE, DIAMOND, LINES, OVAL)
